# Database adapter changed to mysql2 due to foreign key constraints
default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: subonrails
  password: <%= ENV["MYSQL_PASSWD"] %>

development:
  <<: *default
  database: subonrails_dev

production:
  <<: *default
  database: subonrails

# Warning: Do not set this db to the same as development or production.
test:
  <<: *default
  database: subonrails_test
